### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by GeeWee** [peter-woyzbun/rests#4]
I see that in the setup.py we're requiring a lot of different sql clients
`psycopg`, `mssqlclient`, etc.
I've looked through the source code and I don't see them used anywhere.
I'm having trouble installing some of them on my machine, and I was wondering if we could remove them, if they're not actually used.

Great project btw

**Comment by peter-woyzbun** [comment]
Thanks! Just pushed this fix.
